-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: sql207.infinityfree.com
-- Generation Time: Mar 09, 2026 at 02:38 PM
-- Server version: 11.4.10-MariaDB
-- PHP Version: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `if0_41345862_matjar_el_kotobia_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `hri_product`
--

CREATE TABLE `hri_product` (
  `product_id` int(10) UNSIGNED NOT NULL,
  `product_category_id` int(10) UNSIGNED NOT NULL COMMENT 'FK → hri_category.category_id',
  `product_name_fr` varchar(200) NOT NULL COMMENT 'Product name in French',
  `product_name_ar` varchar(200) NOT NULL COMMENT 'Product name in Arabic',
  `product_slug` varchar(220) NOT NULL COMMENT 'URL-safe slug — unique per product',
  `product_description_fr` text DEFAULT NULL COMMENT 'Full description in French',
  `product_description_ar` text DEFAULT NULL COMMENT 'Full description in Arabic',
  `product_price` decimal(10,2) NOT NULL COMMENT 'Regular price in DH (MAD)',
  `product_sale_price` decimal(10,2) DEFAULT NULL COMMENT 'Promotional price in DH — NULL = no sale',
  `product_unit` enum('kg','piece','pack','liter','gram','unit') NOT NULL DEFAULT 'piece' COMMENT 'Unit of measure',
  `product_unit_step` decimal(5,2) NOT NULL DEFAULT 1.00 COMMENT 'Cart quantity increment (e.g. 0.5 for ½ kg)',
  `product_stock_quantity` int(11) NOT NULL DEFAULT 0 COMMENT 'Available stock — 0 = out of stock',
  `product_image` varchar(255) NOT NULL DEFAULT 'default_product.jpg' COMMENT 'Main image filename (assets/uploads/products/)',
  `product_image_thumb` varchar(255) DEFAULT NULL COMMENT 'Thumbnail filename (generated by PHP GD)',
  `product_is_featured` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 = show in homepage featured section',
  `product_is_on_sale` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 = show sale badge overlay',
  `product_is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1 = visible to customers',
  `product_view_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Page-view counter for basic analytics',
  `product_sort_order` int(11) NOT NULL DEFAULT 0 COMMENT 'Custom sort within category',
  `product_created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `product_updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Product catalog — prices in MAD, bilingual FR/AR';

--
-- Dumping data for table `hri_product`
--

INSERT INTO `hri_product` (`product_id`, `product_category_id`, `product_name_fr`, `product_name_ar`, `product_slug`, `product_description_fr`, `product_description_ar`, `product_price`, `product_sale_price`, `product_unit`, `product_unit_step`, `product_stock_quantity`, `product_image`, `product_image_thumb`, `product_is_featured`, `product_is_on_sale`, `product_is_active`, `product_view_count`, `product_sort_order`, `product_created_at`, `product_updated_at`) VALUES
(1, 1, 'Tomates fraîches', 'طماطم طازجة', 'tomates-fraiches', 'Tomates fraîches cultivées localement à Safi. Idéales pour salades, sauces et tajines.', 'طماطم طازجة محلية من سافي. مثالية للسلطات والصلصات والطاجين.', '7.00', NULL, 'kg', '0.50', 100, 'tomates-fraiches.jpg', NULL, 1, 0, 1, 0, 0, '2026-03-09 07:07:16', '2026-03-09 07:07:16'),
(2, 4, 'Lait Central entier 1L', 'حليب سنطرال كامل الدسم 1 لتر', 'lait-central-entier-1l', 'Lait pasteurisé entier Central, 1 litre. Riche en calcium et protéines.', 'حليب مبستر كامل الدسم من سنطرال، 1 لتر. غني بالكالسيوم والبروتينات.', '7.00', NULL, 'liter', '1.00', 80, 'lait-central-1l.jpg', NULL, 0, 0, 1, 0, 0, '2026-03-09 07:07:16', '2026-03-09 07:07:16'),
(3, 6, 'Huile d\'olive extra vierge 1L', 'زيت الزيتون البكر الممتاز 1 لتر', 'huile-olive-extra-vierge-1l', 'Huile d\'olive marocaine extra vierge, première pression à froid. Bouteille 1 litre.', 'زيت زيتون مغربي بكر ممتاز، عصر بارد أول. زجاجة 1 لتر.', '55.00', '45.00', 'liter', '1.00', 50, 'huile-olive-1l.jpg', NULL, 1, 1, 1, 0, 0, '2026-03-09 07:07:16', '2026-03-09 07:07:16'),
(4, 7, 'Eau minérale Sidi Ali 1,5L', 'ماء معدني سيدي علي 1.5 لتر', 'eau-minerale-sidi-ali-1-5l', 'Eau minérale naturelle Sidi Ali, bouteille 1,5 litre. Source des montagnes du Moyen Atlas.', 'ماء معدني طبيعي سيدي علي، قارورة 1.5 لتر. من ينابيع جبال الأطلس المتوسط.', '4.50', NULL, 'liter', '1.00', 200, 'sidi_ali_1,5.jpg', NULL, 1, 0, 1, 0, 0, '2026-03-09 07:07:16', '2026-03-09 07:35:14'),
(5, 6, 'Couscous Dari grain moyen 1kg', 'كسكس داري حبة متوسطة 1 كلغ', 'couscous-dari-grain-moyen-1kg', 'Couscous de blé dur Dari, grain moyen. Sachet 1 kg. Idéal pour le couscous traditionnel du vendredi.', 'كسكس من القمح الصلب داري، حبة متوسطة. كيس 1 كلغ. مثالي لكسكس يوم الجمعة التقليدي.', '18.50', NULL, 'kg', '1.00', 120, 'couscous-dari-1kg.jpg', NULL, 0, 0, 1, 0, 0, '2026-03-09 07:07:16', '2026-03-09 07:07:16');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `hri_product`
--
ALTER TABLE `hri_product`
  ADD PRIMARY KEY (`product_id`),
  ADD UNIQUE KEY `uq_product_slug` (`product_slug`),
  ADD KEY `idx_product_category` (`product_category_id`),
  ADD KEY `idx_product_slug` (`product_slug`),
  ADD KEY `idx_product_active` (`product_is_active`),
  ADD KEY `idx_product_featured` (`product_is_featured`,`product_is_active`),
  ADD KEY `idx_product_sale` (`product_is_on_sale`,`product_is_active`),
  ADD KEY `idx_product_price` (`product_price`),
  ADD KEY `idx_product_stock` (`product_stock_quantity`);
ALTER TABLE `hri_product` ADD FULLTEXT KEY `idx_product_search` (`product_name_fr`,`product_name_ar`,`product_description_fr`,`product_description_ar`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `hri_product`
--
ALTER TABLE `hri_product`
  MODIFY `product_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `hri_product`
--
ALTER TABLE `hri_product`
  ADD CONSTRAINT `fk_product_category` FOREIGN KEY (`product_category_id`) REFERENCES `hri_category` (`category_id`) ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
